### ISSUE TITLE
20.0.1 (20.0_Release) fails to build on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by BTemp1282020** [openpbs/openpbs#2414]
Hello,

I have already fixed a local issue with the with_python.m4 file to support python 3.9 (which ships with Ubuntu 20.04) but I have encountered another issue for which the resolution is not imminently apparent.

post configure, during build, I receive the following error message:

```
gcc -DHAVE_CONFIG_H -I. -I../../../src/include  -I../../../src/include -I../../../src/resmom/    -g -O2 -MT libsite_a-site_mom_chu.o -MD -MP -MF .deps/libsite_a-site_mom_chu.Tpo -c -o libsite_a-site_mom_chu.o `test -f 'site_mom_chu.c' || echo './'`site_mom_chu.c
site_mom_chu.c:61:10: fatal error: mom_mach.h: No such file or directory
   61 | #include "mom_mach.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:629: libsite_a-site_mom_chu.o] Error 1
```

I am running on the default software provided by Ubuntu 20.04 LTS (python 3.9, gcc 9.3.0).

**Comment by BTemp1282020** [comment]
Update: This seems to have been fixed in the master branch.

Is there a timeline on when the updates will be migrated to a release branch?

**Comment by MarceloAros** [comment]
> 
> 
> Update: This seems to have been fixed in the master branch.
> 
> Is there a timeline on when the updates will be migrated to a release branch?

Effectively. Directly clone the repository and the compilation succeeded. However, when starting the pbs, it throws me the following error in "/opt/pbis/sbin/pbs_ds_systemd: 43: [: xrunning: unexpected operator" I would appreciate any suggestion.

**Comment by BTemp1282020** [comment]
you can edit the file to remove the problem.  On the 1st line, I set it to use /bin/bash instead of /bin/sh and that resolved the issue for me
