### ISSUE TITLE
It won't compile in Ubuntu 20.04

### ISSUE THREAD

**Issue by amaurypm** [openpbs/openpbs#1887]
Neither version 20.0.0 or the most recent commit compile in Ubuntu 20.04 (or derivatives).

When executing
```bash
./configure --prefix=/opt/pbs
```
you get:
```
configure: error: Python must be version 3.5
else
  3.6 or 3.7
```

Python 3 in Ubuntu 20.04 is version 3.8.2. If the configure file is edited to accept Python 3.8 them the `make` command fails, with:
```
/usr/bin/ld: openpbs/src/lib/Libpython/pbs_ifl_wrap.c:2735: undefined reference to `PyUnicode_DecodeUTF8'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:790: pbs_server.bin] Error 1
make[2]: Leaving directory 'openpbs/github/openpbs/src/server'
make[1]: *** [Makefile:511: all-recursive] Error 1
make[1]: Leaving directory 'openpbs/src'
make: *** [Makefile:547: all-recursive] Error 1
```

Given that 20.04 is the new LTS version of Ubuntu, it would be great that openpbs could be use in it.

Thank you.

**Comment by kjakkali** [comment]
hi @amaurypm  : [PR](https://github.com/openpbs/openpbs/pull/1898) is adding initial support for Ubuntu20.04.
